### ISSUE TITLE
Replace modal plugin

### ISSUE THREAD

**Issue by patric-eberle** [valantic/vue-template#121]
The used Vue plugin vue-js-modal seems quite big for the functionality we actually use.
https://bundlephobia.com/result?p=vue-js-modal@2.0.0-rc.6

Some features like drag and drop or resizing we never used. I think it would be worth to create our own modal component, which implements the basics to reduce JS size, CSS complexity and makes us more flexible.

This would most likely deprecate #119 #120

**Comment by patric-eberle** [comment]
Related tickets #120, #121, #145, #148

**Comment by janwidmer** [comment]
Ticket is only needed in the Vue-2 scenario
