### ISSUE TITLE
SCSS @import is deprecated

### ISSUE THREAD

**Issue by patric-eberle** [valantic/vue-template#144]
The `@import` rule was marked deprecated. It is replaced by`@use` and `@forward`. Since `@use` also makes use of namespace, we should check if this is something we want to use in the future (e.g. color.$primary-1).

It is currently unclear if this new syntax is supported by our webpack setup.

More details: https://www.youtube.com/watch?v=CR-a8upNjJ0

**Comment by janwidmer** [comment]
Closed via #182
