### ISSUE TITLE
Update to Vue 3

### ISSUE THREAD

**Issue by patric-eberle** [valantic/vue-template#147]
Create a parallel template, that is based on Vue 3. Since IE11 is not yet supported, we will have to use Vue 2 for projects that need to support legacy browsers.

**Comment by patric-eberle** [comment]
Check out the new migration build, which was released with Vue 3.1! https://github.com/vuejs/vue-next/tree/master/packages/vue-compat

**Comment by janwidmer** [comment]
Closed via https://github.com/valantic/vue-template/pull/196.

Vue-3 will stay in a separated branch until further notice
