### ISSUE TITLE
Enhance e-icon to use currentColor attribute for inline icons

### ISSUE THREAD

**Issue by janwidmer** [valantic/vue-template#160]
By using the attribute `currentColor` on svg path / group / ... elements, the color from the parent element will be used. This is quite neat to implement hover / focus states on links / buttons having an icon.

The icon element can be enhanced to replace the primary icon color by `currentColor` for inline icons.

**Comment by patric-eberle** [comment]
Note: Version 2 from #142 will most likely fix this already.

**Comment by janwidmer** [comment]
Obsolete with #142
