### ISSUE TITLE
Refactor notifications

### ISSUE THREAD

**Issue by patric-eberle** [valantic/vue-template#164]
The notification system should be refactored:

- Simplify notification structure (see also #86, #103)
- Reduce to the minimal requirements (show notifications from server globally, in modal, locally [e.g. form field])
- Rebuild related components, simplify structure
- If possible allow to extend data structure and/or functionality as easy as possible.

Check which variants of notifications and position of display are really required by default.

**Comment by janwidmer** [comment]
Closed via #175
