### ISSUE TITLE
Component to translate HTML based translations

### ISSUE THREAD

**Issue by patric-eberle** [valantic/vue-template#167]
To decrease the risk of XSS we should replace the currently used `v-html="$t()"` uses with a dedicated component, that is able to convert most common HTML elements inside translations with the provided interpolation solution.

```
My translation with{br}line{br}breaks.
```

```vue
<template>
  <i18n :path="path" :tag="tag">
    <template #br>
      <br>
    </template>
  </i18n>
</template>

<script>
  export default {
    name: 'e-translation',

    props: {
      path: {
        type: String,
        required: true
      },
      tag: {
        type: String,
        default: ''
      }
    },
  };
</script>
```

NOTE: this should be changed in the whole application. So be careful if applied to existing projects!

**Comment by patric-eberle** [comment]
Note: the example above does only work with self closing tags. You can not use `<h1>...</h1>` for example...

**Comment by patric-eberle** [comment]
Also see https://github.com/kazupon/vue-i18n/issues/898 for a possible alternative.

**Comment by claudio147** [comment]
@patric-eberle Don't you think it's kind of an overkill to create a certain component that handles those translations?
I only remember e few cases where we need some specific tags (except `<br>`) and those we did like it's described here https://kazupon.github.io/vue-i18n/guide/interpolation.html#slots-syntax-usage .

If you just ned line breaks I would prefer to add `\n` in the translated string.

**Comment by patric-eberle** [comment]
@claudio147 yes unfortunately I guess it is not of great use, if we can't also define elements with an opening/closing tag... And I still can't think of an other solution.
