### ISSUE TITLE
Add locale header to Ajax requests

### ISSUE THREAD

**Issue by patric-eberle** [valantic/vue-template#187]
For the backend to be able to return status messages or other translated messages, we should always provide the current page language when making a request to the server. In some projects this is handled by the called URL, but a more solid solution would be to add the current locale as a header value to the API helper.

Example:

```
// api.js
import { PAGE_LANGUAGE } from '@/setup/i18n';

export const axiosInstance = axios.create({
  headers: {
    locale: PAGE_LANGUAGE,
  },
});
```

Warning: the example only works for the store helper. It would be better to also have this on the local `this.$axios` instance!

**Comment by janwidmer** [comment]
Warning: Make sure to NOT send this header when doing requests to Google Services API, as this leads to CORS errors
