### ISSUE TITLE
How to reach out PIMCORE Team for a Demo / Implementation

### ISSUE THREAD

**Issue by Shadabali785** [valantic/vue-template#204]
Hello Guys,

I have been trying to contact PIMCORE team for the last weeks, send several emails at their official email address "info@pimcore.com". Left msgs on Linkedin to their Co-founder/ CEO but got no reply so far.

Can anyone help me out on how I can reach out to PIMCORE team ?

**Comment by pryserv** [comment]
For a general request to Pimcore, I recommend the official way via the contact form on the website https://pimcore.com/en/contact-us.

If you are looking for a certified Pimcore partner for your project, we would be happy to contact you.

**Comment by Shadabali785** [comment]
> For a general request to Pimcore, I recommend the official way via the contact form on the website https://pimcore.com/en/contact-us.
> 
> If you are looking for a certified Pimcore partner for your project, we would be happy to contact you.

Hello, 
I have tried contacting PIMCORE team by filling out their online "Get in touch with us" web form but got no replies.

Yes, we are looking for a certified PIMCORE partner who can work with us in implementing PIM DAM solution.

Can you please suggest a time, so I could schedule a session along with our marketing team and we could start with a PIM DAM detailed demo and Q&A session with our Marketing team and then move forward.

you can directly contact me on my official email "shadab.ali@getzpharma.com"

Regards,

**Comment by pryserv** [comment]
That sounds very interesting. We are a certified Pimcore partner and have already implemented various large projects for different industries. I forwarded your contact request to the appropriate people. Please contact me if you don’t hear anything in the next few days.

What I would like to mention, Pimcore is a perfect choice for the implementation of simple to very complex solutions in the PIM / DAM / MDM / CMS context.

Thanks and regards,
Patrick

**Comment by Shadabali785** [comment]
> That sounds very interesting. We are a certified Pimcore partner and have already implemented various large projects for different industries. I forwarded your contact request to the appropriate people. Please contact me if you don’t hear anything in the next few days.
> 
> What I would like to mention, Pimcore is a perfect choice for the implementation of simple to very complex solutions in the PIM / DAM / MDM / CMS context.
> 
> Thanks and regards, Patrick

Cool. Looking forward to hear from your team soon. Can you please also share your contact details with me, so I could directly contact you in case I hear nothing from your team.
