### ISSUE TITLE
Migrate Vue-i18n from legacy to newest version

### ISSUE THREAD

**Issue by janwidmer** [valantic/vue-template#207]
Vue-i18n is currently used in legacy mode. Migrate it to the new Format by following this guide: https://kazupon.github.io/vue-i18n/legacy/#global-config

**Comment by MB-web** [comment]
It seems that since we are using the options API over the composition API the `legacy`-mode is still preferable.
(It is also still the default mode, regardless of the name `legacy`)

See: https://vue-i18n.intlify.dev/api/general.html
