### ISSUE TITLE
Improve checkbox handling

### ISSUE THREAD

**Issue by mob8607** [valantic/vue-template#243]
- Add interceptable option:
If the checkbox handling has to be intercepted (e.g. displaying a confirmation modal) it can't be handled as default input element. Therefore we can use a button element instead.

Reason:
```It's important to understand that READONLY merely prevents the user from changing the value of the field, not from interacting with the field. In checkboxes, for example, you can check them on or off (thus setting the CHECKED state) but you don't change the value of the field.```

- Add toggle styling as variant.
To achieve this, we can use the current styling of the s-toggle component and integrate it into the e-checkbox.

- Add tag styling as a variant
Will not show a checkbox but only the text label.

**Comment by patric-eberle** [comment]
An example for the `interceptable` option can be found in the MOT project.

**Comment by patric-eberle** [comment]
There is also a `e-checkbox` implementation with 3 `variants` (checkbox, toggle, bullet point) on IV, which is, as of today, the most recent implementation.
