### ISSUE TITLE
Update node/npm version

### ISSUE THREAD

**Issue by benjamin-joham** [valantic/vue-template#305]
The projects node version is currently on 12.14. which maintenance support ran out in 2022.
In order to have a more reliable maintenance and future feature support we should upgrade the node and npm version.

As seen below the best option is to upgrade to node 18 and npm >= 8.6.0

With this change we could also add a `.nvmrc` file with the specified version for an easier setup.

![image](https://user-images.githubusercontent.com/26364566/230009821-1452a2d0-9d3f-4bf1-a288-7138ce8e2458.png)

**Comment by mob8607** [comment]
This is only on master branch. @patric-eberle Is there any plan to update master from one of our feature or develop branches in the near future?

**Comment by patric-eberle** [comment]
@mob8607 Yes. I think we can merge the vite branch into `develop` and from there to `master`. I will do this.
