### ISSUE TITLE
lint-staged

### ISSUE THREAD

**Issue by mob8607** [valantic/vue-template#356]
As soon as some files are staged the `npm run lint-staged` command throws following error:

```
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and 'vue-template/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

**Comment by patric-eberle** [comment]
Note: this error will also be shown if you try to commit.

**Comment by patric-eberle** [comment]
In my opinion it should be able to fix this by using `export default ...` instead of `module.exports`.
